// Generated by CoffeeScript 1.4.0
var pb;

pb = function() {
  var getSelectedText, selectedTextParam, urlParam;
  getSelectedText = function() {
    return window.getSelection() || document.getSelection() || document.selection.createRange().text;
  };
  selectedTextParam = "";
  urlParam = "url=" + encodeURIComponent(document.location);
  if (getSelectedText()) {
    selectedTextParam = "&name=" + encodeURIComponent(getSelectedText());
  }
  return document.location = "<%= ";
};

pb();
